# Specify the configuration version explicitly
version: "2"

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
  goconst:
    min-len: 3
    min-occurrences: 3

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 0
  max-same-issues: 0
  output:
    format: colored-line-number
