# GoReleaser configuration for thinktank
# https://goreleaser.com/customization/
version: 2

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: thinktank
    main: ./cmd/thinktank
    binary: thinktank
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Skip arm64 for Windows (not commonly needed)
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/misty-step/thinktank/internal/version.Version={{.Version}}
      - -X github.com/misty-step/thinktank/internal/version.Commit={{.Commit}}
      - -X github.com/misty-step/thinktank/internal/version.BuildDate={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    # Windows gets zip format
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

changelog:
  # Use release-please's changelog instead of generating our own
  use: github-native

release:
  github:
    owner: misty-step
    name: thinktank
  # Don't mark as draft - release-please handles release creation
  draft: false
  # Keep pre-releases clearly marked
  prerelease: auto
  # Include release notes from release-please
  mode: replace

# Announce new releases (optional)
# announce:
#   skip: true
