# GoReleaser configuration for the thinktank project
# This file configures automated builds and releases for multiple platforms
# Documentation: https://goreleaser.com/customization/

# Project name - defaults to the folder name if not set
project_name: thinktank

# This section defines build configurations
builds:
  - id: thinktank
    # Path to main.go file
    main: ./main.go
    
    # Binary name
    binary: thinktank
    
    # Custom environment variables for build
    env:
      - CGO_ENABLED=0
    
    # Build flags
    flags:
      - -trimpath
    
    # Custom ldflags for version injection
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    
    # GOOS and GOARCH combinations to build
    goos:
      - darwin
      - linux
      - windows
    
    goarch:
      - amd64
      - arm64
    
    # Ignore certain GOOS/GOARCH combinations
    ignore:
      - goos: windows
        goarch: arm64

# Archive configuration
archives:
  - id: default
    # Archive name template
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    
    # Archive format per platform
    format_overrides:
      - goos: windows
        format: zip
    
    # Additional files to include in the archive
    files:
      - LICENSE
      - README.md
      - CONTRIBUTING.md

# Checksum configuration  
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

# Snapshot configuration for non-tagged builds
snapshot:
  name_template: '{{ incpatch .Version }}-next'

# Changelog configuration
# We use git-chglog for changelog generation, so we disable GoReleaser's built-in
changelog:
  # Disable GoReleaser's automatic changelog generation
  skip: true
  
  # Use a custom changelog file generated by git-chglog
  use: git

# GitHub Release configuration
release:
  # GitHub repository
  github:
    owner: phrazzld
    name: thinktank
  
  # Release name template
  name_template: '{{.ProjectName}}-v{{.Version}}'
  
  # Disable automatic publishing for safety
  # This allows manual review before publishing
  draft: true
  
  # Mark as prerelease if version contains alpha, beta, or rc
  prerelease: auto
  
  # Release notes file path (generated by git-chglog)
  # T011: Use pre-generated CHANGELOG.md via --release-notes flag in CI
  # The changelog is generated in the before hooks

# Signs the checksum file using GPG
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sig"
      - "${artifact}"

# Before hooks - commands to run before the release
before:
  hooks:
    # Generate changelog with git-chglog before release
    - git-chglog -o CHANGELOG.md
    # Ensure go mod is tidy
    - go mod tidy
    # Run tests before building
    - go test ./...

# Announce configuration (optional)
announce:
  skip: true  # We don't use automated announcements

# Universal binaries for macOS (combines amd64 and arm64)
universal_binaries:
  - replace: true
    id: thinktank
    # Create universal binary for macOS
    ids:
      - thinktank