# Coverage reporting configuration for PR comments
# See: https://github.com/k1LoW/octocov

coverage:
  paths:
    - coverage.out
  acceptable: 79%

codeToTestRatio:
  code:
    - "internal/**/*.go"
    - "!internal/**/*_test.go"
    - "!internal/testutil/**"
    - "!internal/integration/**"
    - "!internal/e2e/**"
  test:
    - "internal/**/*_test.go"

diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

comment:
  enable: true
  hideFooterLink: false
  deletePrevious: true

report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}

summary:
  enable: true

badge:
  path: docs/coverage/badge.svg
