repos:
# Comprehensive linting (slower but thorough)
-   repo: https://github.com/golangci/golangci-lint
    rev: v1.61.0  # Much newer version
    hooks:
    -   id: golangci-lint
        args: ["--timeout=10m", "--verbose"]

# Comprehensive Go checks
-   repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
    -   id: go-build
    -   id: go-unit-tests
        name: go unit tests
        entry: bash -c "cd './' && go test -short ./cmd/thinktank/... ./internal/thinktank/interfaces ./internal/thinktank/modelproc ./internal/thinktank/prompt ./internal/auditlog ./internal/config ./internal/fileutil ./internal/gemini ./internal/integration ./internal/logutil ./internal/ratelimit"
        pass_filenames: false
        language: system
    -   id: go-test-repo-mod
        name: go test with race detection
        entry: bash -c "cd './' && go test -race -short $(go list ./... | grep -v 'internal/e2e')"
        pass_filenames: false
        language: system

# Coverage and quality checks
-   repo: local
    hooks:
    -   id: check-coverage
        name: Check test coverage threshold
        entry: bash -c "cd './' && ./scripts/check-coverage.sh 75"
        language: system
        pass_filenames: false
    -   id: vulnerability-check
        name: Check for Go vulnerabilities
        entry: bash -c "cd './' && go run golang.org/x/vuln/cmd/govulncheck@latest ./..."
        language: system
        pass_filenames: false
