package logutil

// SummaryData contains the data needed to display the execution summary section.
// It captures the overall results of a thinktank run including model counts,
// synthesis status, and output location.
type SummaryData struct {
	ModelsProcessed  int    // Total number of models attempted
	SuccessfulModels int    // Number of models that completed successfully
	FailedModels     int    // Number of models that failed
	SynthesisStatus  string // "completed", "failed", or "skipped"
	OutputDirectory  string // Path to the directory containing outputs
}

// OutputFile represents a single output file generated by thinktank,
// including its display name, full path, and size for formatting.
type OutputFile struct {
	Name string // Display name of the file (e.g., "gemini-3-flash.md")
	Path string // Full path to the file
	Size int64  // File size in bytes
}

// FailedModel represents a model that failed during processing,
// including the model name and the reason for failure.
type FailedModel struct {
	Name   string // Model name (e.g., "gpt-4o")
	Reason string // Human-readable failure reason (e.g., "rate limited", "API error")
}
