name: PR Size Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  size-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: 'size/XS'
          xs_max_size: 10
          s_label: 'size/S'
          s_max_size: 100
          m_label: 'size/M'
          m_max_size: 200
          l_label: 'size/L'
          l_max_size: 400
          xl_label: 'size/XL'
          fail_if_xl: false
          message_if_xl: >
            This PR exceeds 400 lines. Consider splitting into smaller,
            more reviewable chunks if possible.
